services:
  - type: web
    name: dormshare-backend
    env: docker
    dockerContext: dormshare_android/dormshare-backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: localhost:9092
      - key: SPRING_AUTOCONFIGURE_EXCLUDE
        value: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration,org.springframework.boot.autoconfigure.kafka.KafkaPropertiesAutoConfiguration
